import 'server-only';
import { randomUUID } from 'crypto';
import { getSupabase } from './supabase';
import type { Meeting } from './types';

const fail = (error: { message:string } | null) => { if (error) throw new Error(error.message); };
const detail = '*, meeting_participants(position, participants(*)), transcript_segments(*, participants(*)), decisions(*, transcript_segments(*)), action_items(*, participants(*), transcript_segments(*)), highlights(*, transcript_segments(*)), shares(token, highlight_id, revoked_at)';
const mapMeeting = (row:any):Meeting => {
  const people = (row.meeting_participants ?? []).sort((a:any,b:any)=>a.position-b.position).map((item:any)=>({id:item.participants.id,name:item.participants.name,role:item.participants.role,initials:item.participants.initials,color:item.participants.color}));
  const transcript = (row.transcript_segments ?? []).sort((a:any,b:any)=>a.position-b.position).map((item:any)=>({id:item.id,start:Number(item.starts_at),end:Number(item.ends_at),speaker:item.participant_id ?? 'unknown',text:item.content,chapter:item.chapter}));
  const sourceTime = (source:any) => Number(source?.starts_at ?? 0);
  return { id:row.slug,title:row.title,company:row.company,date:row.occurred_at,duration:row.duration_seconds,kind:row.meeting_kind,color:people[0]?.color ?? '#785d4e',people,transcript,description:row.description,media:row.media_url ?? '',shareToken:(row.shares ?? []).find((share:any)=>!share.revoked_at && !share.highlight_id)?.token ?? '',summary:{purpose:row.brief,takeaways:(row.decisions ?? []).sort((a:any,b:any)=>a.position-b.position).map((decision:any)=>({text:decision.text,time:sourceTime(decision.transcript_segments)})),topics:[],nextSteps:(row.action_items ?? []).sort((a:any,b:any)=>a.position-b.position).map((action:any)=>({text:action.text,time:sourceTime(action.transcript_segments)}))},actions:(row.action_items ?? []).sort((a:any,b:any)=>a.position-b.position).map((action:any)=>({id:action.id,text:action.text,owner:action.owner_participant_id ?? '',time:sourceTime(action.transcript_segments),done:action.completed,dueDate:action.due_date})),highlights:(row.highlights ?? []).map((highlight:any)=>({id:highlight.id,title:highlight.title,type:highlight.kind,start:Number(highlight.starts_at),end:Number(highlight.ends_at),note:highlight.note})) } as Meeting & {shareToken:string};
};
export async function listMeetings() { const {data,error}=await getSupabase().from('meetings').select(detail).order('occurred_at',{ascending:false}); fail(error); return (data??[]).map(mapMeeting); }
export async function getMeetingBySlug(slug:string) { const {data,error}=await getSupabase().from('meetings').select(detail).eq('slug',slug).single(); if(error?.code==='PGRST116' || !data) return null; fail(error); return mapMeeting(data); }
export async function getSharedMeeting(token:string) { const supabase=getSupabase(); const {data:share,error}=await supabase.from('shares').select('meeting_id, highlight_id, revoked_at').eq('token',token).is('revoked_at',null).single(); if(error?.code==='PGRST116' || !share) return null; fail(error); const {data:meeting,error:meetingError}=await supabase.from('meetings').select(detail).eq('id',share.meeting_id).single(); fail(meetingError); if(!meeting) return null; return {meeting:mapMeeting(meeting), highlightId:share.highlight_id}; }
export async function updateAction(id:string, patch:{text?:string;completed?:boolean}) { const {data,error}=await getSupabase().from('action_items').update({...patch,updated_at:new Date().toISOString()}).eq('id',id).select('*').single(); fail(error); return data; }
export async function createHighlight(meetingSlug:string, input:{title:string;startsAt:number;endsAt:number;note:string;sourceSegmentId?:string}) { const meeting=await getMeetingBySlug(meetingSlug); if(!meeting) throw new Error('Meeting not found'); const supabase=getSupabase(); const {data:raw,error:lookupError}=await supabase.from('meetings').select('id,duration_seconds').eq('slug',meetingSlug).single(); fail(lookupError); if(!raw || input.startsAt<0||input.endsAt<=input.startsAt||input.endsAt>raw.duration_seconds) throw new Error('Invalid highlight range'); const {data,error}=await supabase.from('highlights').insert({meeting_id:raw.id,title:input.title.trim(),starts_at:input.startsAt,ends_at:input.endsAt,note:input.note,source_segment_id:input.sourceSegmentId ?? null}).select('*').single(); fail(error); return data; }
export async function deleteHighlight(id:string) { const {error}=await getSupabase().from('highlights').delete().eq('id',id); fail(error); }
export async function createShare(meetingSlug:string, highlightId?:string) { const supabase=getSupabase(); const {data:meeting,error:meetingError}=await supabase.from('meetings').select('id').eq('slug',meetingSlug).single(); fail(meetingError); if(!meeting) throw new Error('Meeting not found'); const token=randomUUID().replaceAll('-',''); const {data,error}=await supabase.from('shares').insert({meeting_id:meeting.id,highlight_id:highlightId ?? null,token}).select('token').single(); fail(error); if(!data) throw new Error('Unable to create share'); return data.token; }
export async function transcriptForMeeting(slug:string) { const supabase=getSupabase(); const {data:meeting,error}=await supabase.from('meetings').select('id').eq('slug',slug).single(); fail(error); if(!meeting) throw new Error('Meeting not found'); const {data,error:segmentsError}=await supabase.from('transcript_segments').select('id, content, starts_at, ends_at, participants(name)').eq('meeting_id',meeting.id).order('position'); fail(segmentsError); return data ?? []; }
