 'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useState } from 'react';
import { Gift, HelpCircle, Search, Settings, UserRound, X } from 'lucide-react';

export function AppShell({ children }: { children: React.ReactNode }) {
  const router = useRouter(); const path = usePathname(); const [query, setQuery] = useState(''); const [panel, setPanel] = useState<'refer'|'help'|'profile'|null>(null); const nav = [{href:'/home',label:'My Calls',match:(value:string)=>value==='/home'||value.startsWith('/meetings')},{href:'/team-calls',label:'Team Calls',match:(value:string)=>value==='/team-calls'},{href:'/playlists',label:'Playlists',match:(value:string)=>value==='/playlists'},{href:'/alerts',label:'Alerts',match:(value:string)=>value==='/alerts'}];
  return <div className="shell"><header className="topbar"><Link className="logo" href="/home">FATHOM<b>▰</b></Link><form className="searchbox" onSubmit={event => { event.preventDefault(); router.push(`/home?q=${encodeURIComponent(query)}`); }}><Search size={18}/><input value={query} onChange={event => setQuery(event.target.value)} aria-label="Search call recordings" placeholder="Search Call Recordings" /></form><nav className="toplinks"><button className="nav-button" onClick={()=>setPanel('refer')}><Gift size={20}/>Refer</button><Link href="/settings"><Settings size={20}/>Settings</Link><button className="nav-button" onClick={()=>setPanel('help')}><HelpCircle size={20}/>Help & Feedback</button><button className="profile-button avatar" onClick={()=>setPanel('profile')} style={{ background:'#5f6988' }} aria-label="Open account menu">MA</button></nav></header><nav className="subnav">{nav.map(item=><Link className={item.match(path)?'active':''} href={item.href} key={item.href}>{item.label}</Link>)}</nav>{children}{panel&&<div className="quick-panel" role="dialog"><button className="quick-close" onClick={()=>setPanel(null)} aria-label="Close"><X size={17}/></button>{panel==='refer'&&<><Gift color="#0bbbed"/><h3>Invite a teammate</h3><p>Share Fathom with someone who should never miss a decision.</p><button onClick={()=>navigator.clipboard?.writeText(window.location.origin)}>Copy invite link</button></>}{panel==='help'&&<><HelpCircle color="#0bbbed"/><h3>Help & Feedback</h3><a href="mailto:help@example.com">Contact support</a><button onClick={()=>setPanel(null)}>Send product feedback</button></>}{panel==='profile'&&<><UserRound color="#0bbbed"/><h3>Muhammad Ahmad</h3><p>Personal workspace</p><Link href="/settings" onClick={()=>setPanel(null)}>Meeting settings</Link></>}</div>}</div>;
}
