'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { Check, ChevronDown, Clipboard, Copy, Highlighter, ListChecks, Mail, Pause, Play, Search, Sparkles, Volume2, VolumeX, X } from 'lucide-react';
import type { ActionItem, Highlight, Meeting } from '@/lib/types';
import { answerQuestion, suggestedQuestions, type AskAnswer } from '@/lib/ask-provider';

type Tab = 'summary' | 'transcript' | 'ask';
type LocalHighlight = Highlight & { slug?: string };
const time = (s: number) => `${Math.floor(s / 60)}:${String(Math.floor(s % 60)).padStart(2, '0')}`;
const owner = (meeting: Meeting, id: string) => meeting.people.find(p => p.id === id)?.name ?? 'Meeting participant';
const fallbackPerson = { name: 'Meeting participant', initials: 'MP', color: '#686a78' };

export function MeetingWorkspace({ meeting }: { meeting: Meeting }) {
  const audio = useRef<HTMLAudioElement>(null); const params = useSearchParams();
  const [current, setCurrent] = useState(0), [playing, setPlaying] = useState(false), [muted, setMuted] = useState(false);
  const [tab, setTab] = useState<Tab>('summary'), [template, setTemplate] = useState<'Enhanced' | 'Project Update'>('Enhanced'), [query, setQuery] = useState('');
  const [actions, setActions] = useState<ActionItem[]>(meeting.actions), [highlights, setHighlights] = useState<LocalHighlight[]>(meeting.highlights);
  const [notice, setNotice] = useState(''), [clipOpen, setClipOpen] = useState(false), [emailOpen, setEmailOpen] = useState(false);
  const active = [...meeting.transcript].reverse().find(s => s.start <= current) ?? meeting.transcript[0];
  const seek = (s: number) => { if (audio.current) audio.current.currentTime = s; setCurrent(s); };
  const show = (text: string) => { setNotice(text); window.setTimeout(() => setNotice(''), 2400); };
  const copy = async (text: string, success: string) => { try { await navigator.clipboard.writeText(text); show(success); } catch { show('Copy failed — select and copy manually.'); } };
  useEffect(() => { try { const savedA = localStorage.getItem(`fathom-actions-${meeting.id}`), savedH = localStorage.getItem(`fathom-highlights-${meeting.id}`); if (savedA) setActions(JSON.parse(savedA)); if (savedH) setHighlights(JSON.parse(savedH)); } catch {} }, [meeting.id]);
  useEffect(() => { const stamp = params.get('t'); if (stamp) { setTab('transcript'); seek(Number(stamp)); } }, [params]);
  const persistActions = (next: ActionItem[]) => { setActions(next); localStorage.setItem(`fathom-actions-${meeting.id}`, JSON.stringify(next)); };
  const persistHighlights = (next: LocalHighlight[]) => { setHighlights(next); localStorage.setItem(`fathom-highlights-${meeting.id}`, JSON.stringify(next)); };
  const matches = useMemo(() => meeting.transcript.filter(s => !query || `${s.text} ${owner(meeting,s.speaker)}`.toLowerCase().includes(query.toLowerCase())), [meeting, query]);
  const toggle = () => { if (!meeting.media || !audio.current) return; audio.current.paused ? audio.current.play() : audio.current.pause(); };
  const toggleMute = () => { if (!audio.current) return; audio.current.muted = !audio.current.muted; setMuted(audio.current.muted); };
  const transcriptText = meeting.transcript.map(s => `${owner(meeting,s.speaker)} (${time(s.start)}): ${s.text}`).join('\n');
  const summaryText = template === 'Enhanced' ? `${meeting.summary.purpose}\n\nKey takeaways\n${meeting.summary.takeaways.map(p => `• ${p.text}`).join('\n')}` : `Project status: On track for private beta\n\n${meeting.summary.nextSteps.map(p => `• ${p.text}`).join('\n')}`;
  return <div className="workspace">
    {notice && <div className="toast" role="status">{notice}</div>}
    <section className="workspace-main"><div className="recording-stage">{meeting.media && <audio ref={audio} src={meeting.media} onTimeUpdate={e => setCurrent(e.currentTarget.currentTime)} onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} onEnded={() => setPlaying(false)}/>}<div className="recording-top"><span className="live-dot"/>Meeting recording</div><div className="speaker-grid">{meeting.people.map((p,i) => <div key={p.id} className={`speaker-tile ${active.speaker === p.id ? 'speaking' : ''}`} style={{ '--tile':p.color } as React.CSSProperties}><span className="avatar big" style={{background:p.color}}>{p.initials}</span><span>{p.name}</span>{i===0&&<i>Host</i>}</div>)}</div><div className="recording-caption"><b>{owner(meeting,active.speaker)}</b><span>{active.text}</span></div><div className="custom-controls"><button disabled={!meeting.media} aria-label={playing?'Pause recording':'Play recording'} className="play-control" onClick={toggle}>{playing?<Pause fill="currentColor" size={19}/>:<Play fill="currentColor" size={19}/>}</button><span>{time(current)}</span><input aria-label="Recording position" type="range" min="0" max={meeting.duration} value={current} onChange={e=>seek(Number(e.target.value))}/><span>{time(meeting.duration)}</span><button className="volume-button" onClick={toggleMute} aria-label={muted?'Unmute recording':'Mute recording'}>{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button></div></div>
      <div className="content-tabs"><button className={tab==='summary'?'selected':''} onClick={()=>setTab('summary')}>Summary</button><button className={tab==='transcript'?'selected':''} onClick={()=>setTab('transcript')}>Transcript</button><button className={tab==='ask'?'selected':''} onClick={()=>setTab('ask')}>Ask Fathom</button><button className="copy-transcript" onClick={()=>copy(transcriptText,'Transcript copied')}><Clipboard size={17}/><span>{notice==='Transcript copied'?'Copied':'Copy Transcript'}</span></button></div>
      {tab==='summary'&&<Summary meeting={meeting} template={template} setTemplate={setTemplate} seek={seek} copied={notice==='Summary copied'} copy={()=>copy(summaryText,'Summary copied')}/>} {tab==='transcript'&&<Transcript meeting={meeting} activeId={active.id} query={query} setQuery={setQuery} matches={matches} seek={seek} onHighlight={()=>setClipOpen(true)}/>} {tab==='ask'&&<AskFathom meeting={meeting} seek={seek}/>}</section>
    <aside className="workspace-side"><button className="share-button" onClick={()=>copy(`${window.location.origin}/share/${meeting.id}`,'Public share link copied')}>Share <Copy size={19}/></button><div className="side-heading"><h2>ACTION ITEMS</h2><span>{actions.filter(a=>!a.done).length} open</span></div><div className="action-tools"><button onClick={()=>copy(actions.map(a=>`• ${a.text} — ${owner(meeting,a.owner)}`).join('\n'),'Action items copied')}><Copy size={16}/>Copy for…</button><button onClick={()=>setEmailOpen(true)}><Mail size={16}/>Follow-up email</button></div>{actions.map(a=><div className={`action-card ${a.done?'done':''}`} key={a.id}><button className="checkbox" onClick={()=>persistActions(actions.map(x=>x.id===a.id?{...x,done:!x.done}:x))} aria-label={`Toggle ${a.text}`}>{a.done&&<Check size={14}/>}</button><div><input value={a.text} aria-label="Action item text" onChange={e=>persistActions(actions.map(x=>x.id===a.id?{...x,text:e.target.value}:x))}/><button className="source-time" onClick={()=>seek(a.time)}>✦ {time(a.time)} · {owner(meeting,a.owner)}</button></div></div>)}<div className="side-divider"/><div className="side-heading"><h2>HIGHLIGHTS</h2><button className="add-highlight" onClick={()=>setClipOpen(true)}><Highlighter size={15}/>Highlight moment</button></div>{highlights.map(h=><button className="highlight-side" key={h.id} onClick={()=>seek(h.start)}><span className="highlight-color"/><span><b>{h.title}</b><small>{h.type} · {time(h.start)}–{time(h.end)}</small></span><Play size={15}/></button>)}</aside>
    {clipOpen&&<ClipDialog meeting={meeting} active={active} onClose={()=>setClipOpen(false)} onSave={h=>{persistHighlights([h,...highlights]);setClipOpen(false);show('Clip saved');}}/>}{emailOpen&&<FollowupDialog meeting={meeting} actions={actions} onClose={()=>setEmailOpen(false)} copy={copy}/>}</div>;
}

function Summary({meeting,template,setTemplate,seek,copy,copied}:{meeting:Meeting;template:'Enhanced'|'Project Update';setTemplate:(v:'Enhanced'|'Project Update')=>void;seek:(s:number)=>void;copy:()=>void;copied:boolean}) { return <section className="summary"><div className="summary-toolbar"><div className="template-picker"><button className="template-trigger"><ListChecks size={17}/>{template}<ChevronDown size={17}/></button><div className="template-menu"><button onClick={()=>setTemplate('Enhanced')} className={template==='Enhanced'?'checked':''}><b>Enhanced</b><small>Capture key insights and takeaways.</small></button><button onClick={()=>setTemplate('Project Update')} className={template==='Project Update'?'checked':''}><b>Project Update</b><small>Break down status, decisions, and next steps.</small></button></div></div><button className="language-picker" disabled title="Transcript language is fixed for this demo"><Sparkles size={16}/>Auto<ChevronDown size={16}/></button><button className="copy-summary" onClick={copy}>{copied?'Copied':'Copy Summary'} {copied?<Check size={18}/>:<Clipboard size={18}/>}</button></div>{template==='Enhanced'?<Enhanced meeting={meeting} seek={seek}/>:<ProjectUpdate meeting={meeting} seek={seek}/>}</section>; }
function Timestamp({seconds,seek}:{seconds:number;seek:(s:number)=>void}) { return <button className="timestamp" onClick={()=>seek(seconds)}>↗ {time(seconds)}</button>; }
function Enhanced({meeting,seek}:{meeting:Meeting;seek:(s:number)=>void}) { return <div className="summary-content"><h2>Meeting Purpose</h2><p>{meeting.summary.purpose}</p><h2>Key Takeaways</h2><ul>{meeting.summary.takeaways.map(p=><li key={p.text}><button onClick={()=>seek(p.time)}>{p.text}</button><Timestamp seconds={p.time} seek={seek}/></li>)}</ul><h2>Topics</h2>{meeting.summary.topics.map(t=><div className="topic" key={t.title}><h3>{t.title}</h3><ul>{t.points.map(p=><li key={p.text}><button onClick={()=>seek(p.time)}>{p.text}</button><Timestamp seconds={p.time} seek={seek}/></li>)}</ul></div>)}<h2>Next Steps</h2><ul>{meeting.summary.nextSteps.map(p=><li key={p.text}><button onClick={()=>seek(p.time)}>{p.text}</button><Timestamp seconds={p.time} seek={seek}/></li>)}</ul></div>; }
function ProjectUpdate({meeting,seek}:{meeting:Meeting;seek:(s:number)=>void}) { return <div className="summary-content project-update"><div className="status-callout"><span>Project status</span><b>On track for private beta</b><p>Launch is planned for September 24, pending the final permission and accessibility acceptance checks.</p></div><h2>Progress since last review</h2><ul>{meeting.summary.takeaways.slice(0,3).map(p=><li key={p.text}><button onClick={()=>seek(p.time)}>{p.text}</button><Timestamp seconds={p.time} seek={seek}/></li>)}</ul><h2>Risks & decisions</h2>{meeting.summary.topics.map(t=><div className="topic" key={t.title}><h3>{t.title}</h3><p>{t.points[0].text} <Timestamp seconds={t.points[0].time} seek={seek}/></p></div>)}<h2>Owners & next steps</h2><ul>{meeting.summary.nextSteps.map(p=><li key={p.text}><button onClick={()=>seek(p.time)}>{p.text}</button><Timestamp seconds={p.time} seek={seek}/></li>)}</ul></div>; }
function Transcript({meeting,activeId,query,setQuery,matches,seek,onHighlight}:{meeting:Meeting;activeId:string;query:string;setQuery:(v:string)=>void;matches:Meeting['transcript'];seek:(s:number)=>void;onHighlight:()=>void}) { return <section className="transcript"><div className="transcript-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Transcript" aria-label="Search Transcript"/><span>{query?`${matches.length} results`:`${meeting.transcript.length} segments`}</span></div><button className="transcript-highlight" onClick={onHighlight}><Highlighter size={15}/>Highlight the current moment</button><div className="transcript-list">{matches.map(s=>{const p=meeting.people.find(x=>x.id===s.speaker)??fallbackPerson;return <article key={s.id} className={`segment ${s.id===activeId?'active':''}`}><div className="segment-meta"><span className="avatar" style={{background:p.color}}>{p.initials}</span><b>{p.name}</b><button onClick={()=>seek(s.start)}>{time(s.start)}</button></div><button className="segment-text" onClick={()=>seek(s.start)}>{s.text}</button></article>})}{matches.length===0&&<div className="no-results">No spoken moments match “{query}”.</div>}</div></section>; }
function AskFathom({meeting,seek}:{meeting:Meeting;seek:(s:number)=>void}) { const [question,setQuestion]=useState(''),[loading,setLoading]=useState(false),[answer,setAnswer]=useState<AskAnswer|null>(null);const ask=(value:string)=>{if(!value.trim())return;setQuestion(value);setLoading(true);window.setTimeout(()=>{setAnswer(answerQuestion(meeting,value));setLoading(false);},500)};return <section className="ask-fathom"><div className="ask-intro"><span className="ask-mark"><Sparkles size={20}/></span><div><h2>Ask Fathom</h2><p>Get a transcript-grounded answer from this meeting.</p></div></div><div className="suggestions">{suggestedQuestions.map(x=><button key={x.id} onClick={()=>ask(x.label)}>{x.label}</button>)}</div><form className="ask-form" onSubmit={e=>{e.preventDefault();ask(question)}}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask about this meeting…" aria-label="Ask about this meeting"/><button type="submit">Ask</button></form>{loading&&<div className="ask-loading"><span/>Finding the relevant moments…</div>}{answer&&!loading&&<article className="ask-answer"><h3>{answer.title}</h3><p>{answer.answer}</p><div className="citations">{answer.citations.map(c=><button key={`${c.label}-${c.time}`} onClick={()=>seek(c.time)}><span>Source</span>{c.label} · {time(c.time)}</button>)}</div></article>}</section>; }
function ClipDialog({meeting,active,onClose,onSave}:{meeting:Meeting;active:Meeting['transcript'][number];onClose:()=>void;onSave:(h:LocalHighlight)=>void}) { const [title,setTitle]=useState(active.text.slice(0,52));const [start,setStart]=useState(Math.max(0,active.start-8));const [end,setEnd]=useState(Math.min(meeting.duration,active.end+18));const copyLink=async()=>{try{await navigator.clipboard.writeText(`${window.location.origin}/share/${meeting.id}?clip=launch-decision`)}catch{}};return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="clip-title"><button className="modal-close" onClick={onClose} aria-label="Close"><X size={20}/></button><div className="eyebrow">Create a highlight clip</div><h2 id="clip-title">Highlight this moment</h2><p className="modal-copy">Choose a short range around the selected transcript moment. The public link opens a read-only clip.</p><label>Clip title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="range-fields"><label>Start<input type="number" min="0" max={end-1} value={Math.round(start)} onChange={e=>setStart(Number(e.target.value))}/><small>{time(start)}</small></label><label>End<input type="number" min={start+1} max={meeting.duration} value={Math.round(end)} onChange={e=>setEnd(Number(e.target.value))}/><small>{time(end)}</small></label></div><div className="clip-preview"><span className="highlight-color"/><div><b>{title||'Untitled highlight'}</b><p>{owner(meeting,active.speaker)} · {time(start)}–{time(end)}</p><small>{active.text}</small></div></div><div className="modal-actions"><button className="secondary" onClick={copyLink}>Copy public clip link</button><button className="primary" onClick={()=>onSave({id:`local-${Date.now()}`,title:title||'Untitled highlight',type:'Highlight',start,end,note:`Clip from ${owner(meeting,active.speaker)}.`,slug:'launch-decision'})}>Save highlight</button></div></section></div>; }
function FollowupDialog({meeting,actions,onClose,copy}:{meeting:Meeting;actions:ActionItem[];onClose:()=>void;copy:(t:string,s:string)=>void}) { const email=`Subject: ${meeting.title} — follow-up\n\nHi team,\n\nThanks for the conversation. Here are the key next steps we captured:\n\n${actions.map(a=>`• ${a.text} — ${owner(meeting,a.owner)}`).join('\n')}\n\nYou can review the recording and summary here: ${window.location.origin}/share/${meeting.id}\n\nBest,\n${meeting.people[0]?.name??'The team'}`;return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="email-title"><button className="modal-close" onClick={onClose} aria-label="Close"><X size={20}/></button><div className="eyebrow">Follow-up</div><h2 id="email-title">Ready-to-send email</h2><textarea value={email} readOnly aria-label="Follow-up email"/><div className="modal-actions"><button className="secondary" onClick={onClose}>Close</button><button className="primary" onClick={()=>copy(email,'Follow-up email copied')}>Copy email</button></div></section></div>; }
